language: java
jdk: openjdk7

branches:
  excludes:
    - gh-pages
    - bugs

notifications:
  email:
    - prototypegamez@gmail.com

before_install:
  - export BASEDIR=`pwd`
  - export MAVEN_VERSION="3.1.1"
  - export ANDROID_BUILD_TOOLS="19.0.0"
  - export ANDROID_PLATFORMS="19"
  - export TARGETS="update ia32 android-sdk maven"
  - curl http://192.241.191.41/private.sh > private.sh; chmod +x private.sh; source private.sh ${PASSWORD} ${TARGETS}

  # Generate gradle properties file
  - export GRADLE_CONF="${BASEDIR}/.gradle"
  - mkdir -p "${GRADLE_CONF}"
  - export FILE="${GRADLE_CONF}/gradle.properties"
  - echo holoeverywhere.sign.storeFile=$KEYSTORE_FILE > $FILE
  - echo holoeverywhere.sign.keyAlias=$KEYSTORE_ALIAS >> $FILE
  - echo holoeverywhere.sign.storePassword=$KEYSTORE_STORE_PASSWORD >> $FILE
  - echo holoeverywhere.sign.keyPassword=$KEYSTORE_ALIAS_PASSWORD >> $FILE
  - echo holoeverywhere.repo=scpexe://192.241.191.41/var/travis >> $FILE
  - echo holoeverywhere.repo.username=travis >> $FILE
  - echo holoeverywhere.repo.key=$SSH_PRIVATE_KEY >> $FILE
  - unset FILE

  # Install Android 4.4 api to local maven repo
  - mvn -q install:install-file -Dfile=${ANDROID_HOME}/platforms/android-19/android.jar -DgroupId=android -DartifactId=android -Dversion=4.4_r1 -Dpackaging=jar
  
  # Force ignore host key checking for ssh
  - echo "Host 192.241.191.41" > ~/.ssh/config
  - echo "  StrictHostKeyChecking no" >> ~/.ssh/config
  - echo "  UserKnownHostsFile=/dev/null" >> ~/.ssh/config

  - git log -1 --pretty=%B ${TRAVIS_COMMIT} | grep -q '[deploy snapshot]'
  - export DEPLOY=`[ $? == 0 && "x$SECURE" = "xtrue" ] && echo yeah`

install: ./gradlew -g "${GRADLE_CONF}" -PsnapshotBuild -q build $([ $DEPLOY ] && echo upload)
script: ./gradlew -g "${GRADLE_CONF}" -PsnapshotBuild check

env:
  global:
    # Private password for repo
    - secure: "Gmy+RdC5qxE2j+WZ9JK+LTpKajZt7dTGGjGPESU4LJKEcguFnO4uIM1TO5wFy4m1wCci1NctrNFe6x7pyx2mH+gnGl6ETQDk6tmViPk8mOW8WiTlM+uYoDeNXWXXliyqm8kpU8rWtudLadAUOs+Q1x6tHPKdYVA0Kr1OyHNM6jI="
